name: Github Repository Deployment

on:
  workflow_call:
    inputs:
      repository:
        description: 'Maven repository (distribution management) for deploying the artifacts'
        default: 'github'
        required: false
        type: string
      profile:
        description: 'Maven profile for deployment'
        default: 'deployment-github'
        required: false
        type: string
      jdk:
        description: 'JDK version to use'
        default: 11
        required: false
        type: number
    secrets:
      token:
        description: 'Github security token'
        required: true

jobs:
  deploy:
    name: Deploy
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 

    steps:
    - name: Check-out
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Set up JDK ${{ inputs.jdk }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.jdk }}
        distribution: 'adopt'
        server-id: ${{ inputs.repository }}
        cache: 'maven'
    - name: Build
      run: mvn clean package -B -P ${{ inputs.profile }} -DskipTests
    - name: Deploy
      run: mvn deploy -B -P ${{ inputs.profile }} -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
