name: Testing and validation

on:
  workflow_call:
    inputs:
      jdk:
        description: 'JDK version to use'
        default: 11
        required: false
        type: number

jobs:
  unit_test:
    name: Unit tests with JDK ${{ inputs.jdk }}
    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v3
    - name: Set up JDK ${{ inputs.jdk }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.jdk }}
        distribution: 'adopt'
        cache: 'maven'
    - name: Run unit tests
      run: mvn test

  integration_test:
    name: Integration tests with JDK ${{ inputs.jdk }}
    needs: unit_test
    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v3
    - name: Set up JDK ${{ inputs.jdk }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.jdk }}
        distribution: 'adopt'
        cache: 'maven'
    - name: Run up to integration tests
      run: mvn verify
